### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 29: ordinal not in range(128)

### ISSUE THREAD

**Issue by AlexandreBeauduin** [amorphic/coverlovin#2]
Hello,

first time user, first use on my big library !

got this error:

`album details found: PMD/Business Is Business in PMD - 01 - Intro.mp3
Traceback (most recent call last):
  File "./coverlovin.py", line 273, in <module>
    sys.exit(main())
  File "./coverlovin.py", line 256, in main
    musicDirs = process_dir(musicDir, coverFiles=coverFiles)
  File "./coverlovin.py", line 150, in process_dir
    results = process_dir(dir, results=results, coverFiles=coverFiles)
  File "./coverlovin.py", line 150, in process_dir
    results = process_dir(dir, results=results, coverFiles=coverFiles)
  File "./coverlovin.py", line 150, in process_dir
    results = process_dir(dir, results=results, coverFiles=coverFiles)
  File "./coverlovin.py", line 150, in process_dir
    results = process_dir(dir, results=results, coverFiles=coverFiles)
  File "./coverlovin.py", line 150, in process_dir
    results = process_dir(dir, results=results, coverFiles=coverFiles)
  File "./coverlovin.py", line 173, in process_dir
    log.info("album details found: %s/%s in %s" % (artist, album, file))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 29: ordinal not in range(128)`

What does it means? 

Thanks,

pudeldoodle

**Comment by amorphic** [comment]
Hello, sorry it's taken so long for me to reply.

I've not worked on Coverlovin in a while but I think I need to revisit it as a couple of people have reported similar errors.

Can you tell me the id3 tags for _artist_ and _album_ on the file `PMD/Business Is Business in PMD - 01 - Intro.mp3`? Even better if you can send me the file via email...
